---
title: "Naive Bayes"
output: html_notebook
---
HouseVotes84
```{r}
## Categorical data only:
data(HouseVotes84, package = "mlbench")
head(HouseVotes84, 5)
library(e1071)
model <- naiveBayes(Class ~ ., data = HouseVotes84)
predict(model, HouseVotes84[1:10,-1])
predict(model, HouseVotes84[1:10,-1], type = "raw")

pred <- predict(model, HouseVotes84[,-1])
table(pred, HouseVotes84$Class)
```
Titanic
```{r}
## Example of using a contingency table:
data(Titanic)
mm <- naiveBayes(Survived ~ ., data = Titanic)
mm
predict(mm, as.data.frame(Titanic)[,1:3])
```
```{r}
plot(function(x) dnorm(x, mm$tables$Class[1,1], mm$tables$Class[1,2]), 0, 8, col="red", main="Titanic Distributons", ylab = "y")
curve(dnorm(x, mm$tables$Sex[2,1], mm$tables$Sex[2,2]), add=TRUE, col="blue")
```

Iris
```{r}
## Example with metric predictors:
data(iris)
m <- naiveBayes(Species ~ ., data = iris)
## alternatively:
m <- naiveBayes(iris[,-5], iris[,5])
m
table(predict(m, iris[,-5]), iris[,5])
```
```{r}
par(mfrow=c(2, 2))
plot(function(x) dnorm(x, m$tables$Sepal.Length[1,1], m$tables$Sepal.Length[1,2]), 0 , 8, col="red", main="Sepal Length Distributons", ylab = "y")
curve(dnorm(x, m$tables$Sepal.Length[2,1], m$tables$Sepal.Length[2,2]), add=TRUE, col="blue")
curve(dnorm(x, m$tables$Sepal.Length[3,1], m$tables$Sepal.Length[3,2]), add=TRUE, col="green")

plot(function(x) dnorm(x, m$tables$Sepal.Width[1,1], m$tables$Sepal.Width[1,2]), 0 , 8, col="red", main="Sepal Width Distributons", ylab = "y")
curve(dnorm(x, m$tables$Sepal.Width[2,1], m$tables$Sepal.Width[2,2]), add=TRUE, col="blue")
curve(dnorm(x, m$tables$Sepal.Width[3,1], m$tables$Sepal.Width[3,2]), add=TRUE, col="green")

plot(function(x) dnorm(x, m$tables$Petal.Length[1,1], m$tables$Petal.Length[1,2]), 0 , 8, col="red", main="Petal Length Distributons", ylab = "y")
curve(dnorm(x, m$tables$Petal.Length[2,1], m$tables$Petal.Length[2,2]), add=TRUE, col="blue")
curve(dnorm(x, m$tables$Petal.Length[3,1], m$tables$Petal.Length[3,2]), add=TRUE, col="green")

plot(function(x) dnorm(x, m$tables$Petal.Width[1,1], m$tables$Petal.Width[1,2]), 0 , 8, col="red", main="Petal Width Distributons", ylab = "y")
curve(dnorm(x, m$tables$Petal.Width[2,1], m$tables$Petal.Width[2,2]), add=TRUE, col="blue")
curve(dnorm(x, m$tables$Petal.Width[3,1], m$tables$Petal.Width[3,2]), add=TRUE, col="green")
```