---
title: "Iris Data k-Nearest-Neighbour"
output: html_notebook
---
Data IRIS:
```{r}
iris
```

```{r}
summary(iris)
```
```{r}
pairs(main="Iris Data", iris, col=iris$Species)
```
```{r}
plot.ts(main="Iris Data", iris)
```
```{r}
d <- data.frame(Sepal.Length = iris$Sepal.Length, Sepal.Width = iris$Sepal.Width, Petal.Length = iris$Petal.Length, Petal.Width = iris$Petal.Width)
m <- cor(d)
library('corrplot')
corrplot(m, method="circle")
```

Example 0
```{r}
train <- rbind(iris3[1:25,,1], iris3[1:25,,2], iris3[1:25,,3])
test <- rbind(iris3[26:50,,1], iris3[26:50,,2], iris3[26:50,,3])
cl <- factor(c(rep("s",25), rep("c",25), rep("v",25)))
require(class)
iris_pred <- knn(train, test, cl, k = 3, prob=TRUE)
iris_pred
```

Create build index:
```{r}
testidx <- which(1:length(iris[,1])%%3==0)
```
separate training data from test:
```{r}
iristrain <- iris[-testidx,]
```
```{r}
iristest <- iris[testidx,]
```
                                     Example 1 (Petal.Width).
####
Prepare Data Iris:

Build a learn model: (for petal.width attribute)
```{r}
model <- lm(Petal.Width~., data=iristrain)
```
Use model for prediction the test data
```{r}
prediciton <- predict(model, newdata=iristest)
```
Check correlation with current result, but why ? 
```{r}
cor(prediciton, iristest$Petal.Width)
```
Show result:
```{r}
summary(model)
```