---
title: "PCA-Example with Prestige Data"
output: html_notebook
---
```{r}
require(car)
```
Clear and divide data:
```{r}
clearedPrestige <- Prestige[complete.cases(Prestige),]
# divide data
numericalValues <- clearedPrestige[, 1:5]
ordinalValues <- clearedPrestige[, 6]
# clear data from inf-values
numericalValues[is.infinite(numericalValues$women),] <- 0.00
```
Normalize data with z-scores
```{r}
normalizedData <- scale(numericalValues)
summary(normalizedData)
```
```{r}
par(mfrow=c(2, 2))
hist(clearedPrestige$income, main="Income", xlab = "Income")
hist(clearedPrestige$prestige, main="Prestige", xlab = "Prestige")
hist(normalizedData[,2], main="Normalized income", xlab = "Income")
hist(normalizedData[,4], main="Normalized prestige", xlab = "Prestige")
```
Show PCA-Data
```{r}
pca <- prcomp(normalizedData, center=TRUE, scale. = TRUE)
pca
```
```{r}
plot(pca, main="PCA-Data")
```
Result:
```{r}
biplot(pca, cex=0.6, expand=1)
pdf("PCA-Plot-Prestige-Data.pdf", biplot(pca, cex=0.6, expand=1))
```