---
title: "PCA-Example with Wine Data"
output: html_notebook
---
Read Data from file
```{r}
library("httr")
a <- GET("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")
df <- read.csv(textConnection(content(a)), header=F)
df
```
Clear and divide data:
```{r}
# clearedPrestige <- Prestige[complete.cases(Prestige),]
# divide data
numericalValues <- df[, 2:14]
ordinalValues <- df[, 1]
# clear data from inf-values
numericalValues[is.infinite(numericalValues$women),] <- 0.00
```
Normalize data with z-scores
```{r}
normalizedData <- scale(numericalValues)
summary(normalizedData)
```
```{r}
# par(mfrow=c(2, 2))
# hist(clearedPrestige$income, main="Income", xlab = "Income")
# hist(clearedPrestige$prestige, main="Prestige", xlab = "Prestige")
# hist(normalizedData[,2], main="Normalized income", xlab = "Income")
# hist(normalizedData[,4], main="Normalized prestige", xlab = "Prestige")
```
Show PCA-Data
```{r}
pca <- prcomp(normalizedData, center=TRUE, scale. = TRUE)
pca
```
```{r}
plot(pca, main="PCA-Data")
```
Result:
```{r}
biplot(pca, cex=0.6, expand=1)
# pdf("PCA-Plot-Prestige-Data.pdf", biplot(pca, cex=0.6, expand=1))
```